# Package
version = "0.2"
author = "OnsetGame"
description = "Falcon slots game server"
license = "MIT"

requires "https://github.com/yglukhov/nest"
requires "nake"
requires "nuuid"
requires "nimongo"
requires "https://github.com/onionhammer/nim-templates"
requires "https://github.com/Tormund/boolseq"
requires "jwt"
requires "nimSHA2"
requires "hmac"
